#[lab]
src = "{HOME}/Documents/Vaults/Notes"
dst = "docs"

ignored = [
    ".git",
    ".obsidian",
    ".DS_Store"
]

publish = [
    "Business",
    #
    "Projects/Cython+",
    "Projects/Python to WASM Compiler",
    #
    "Tech",
    #
    "Cheat Sheets",
]
