#[lab]
src = "{HOME}/Documents/Vaults/Notes"
dst = "docs"

ignored = [
    ".git",
    ".obsidian",
    ".DS_Store"
]

publish = [
    "Business",
    #
    "Projects/Cython+",
    "Projects/Python to WASM Compiler",
    #
    "Tech/Apps",
    "Tech/Architecture",
    "Tech/Cloud",
    "Tech/Containers",
    "Tech/Documentation",
    "Tech/Databases",
    "Tech/FOSS",
    "Tech/Machine Learning",
    "Tech/Modeling",
    "Tech/Persistence",
    "Tech/Programming Techniques",
    "Tech/Programming Languages",
    "Tech/Python",
    "Tech/Search",
    "Tech/Security",
    "Tech/Software Engineering",
    "Tech/Tools",
    "Tech/Web",
    #
    "Cheat Sheets",
]
