#[lab]
src = "{HOME}/Documents/Vaults/Notes/Public"
dst = "docs"

ignored = [
    ".git",
    ".obsidian",
    ".DS_Store"
]

# Not used
#publish = [
#    "Business",
#    #
#    "Projects/Cython+",
#    "Projects/Python to WASM Compiler",
#    #
#    "Tech",
#    #
#    "Cheat Sheets",
#]
