[tool.poetry]
name = "lab.abilian.com"
version = "0.1.0"
description = ""
authors = ["Stefane Fermigier <sf@abilian.com>"]

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.4.2"
mkdocs-material = "^9.0.12"
mkdocs-material-extensions = "^1.1.1"
mkdocs-roamlinks-plugin = "^0.2.0"

[tool.poetry.dev-dependencies]
devtools = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
